spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tictactoe
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false